CANVAS_WIDTH=window.innerWidth;
CANVAS_HEIGHT=800;

rotation_angle=-87.99999999999245;
rotation_anglex=7.669999999999859;
// rotation_angle=0
// rotation_anglex=0



increment=0.005
//board
BOARD_WIDTH=1
BOARD_HEIGHT=0.1
BOARD_LENGTH=2
// START_BOARD_x=20;
// START_BOARD_y=20;
// START_BOARD_z=20;
START_BOARD_x=0;
START_BOARD_y=0;
START_BOARD_z=1 ;


LEG_WIDTH=20
LEG_HEIGHT=100
START_LEG_x=START_BOARD_x+10
START_LEG_y=START_BOARD_y+BOARD_HEIGHT
START_LEG_z=START_BOARD_z+10

START_LEG_xr=START_BOARD_x+BOARD_WIDTH-10


NET_WIDHT=BOARD_WIDTH+10
NET_HEIGHT=20
START_NET_x=START_BOARD_x+(NET_WIDHT-BOARD_WIDTH)/2
START_NET_y=START_BOARD_y-NET_HEIGHT
START_NET_z=START_BOARD_z+(BOARD_LENGTH/2)

TABLE_COLOR=["green","transparent","transparent","brown"]
//bat
BAT_WIDTH=20
BAT_HEIGHT=20
BAT_LENGTH=1

//ball
BALL_RADIUS=5

GRAVITY=0.0009

FLOORSTART_Y=800
LOSS=0

